### ISSUE TITLE
Promises not working 

### ISSUE THREAD

**Issue by shaheryar1** [jublonet/codebird-js#159]
**TypeError: cb.__call(...).then is not a function**
    at router.get (C:\Users\EG\Desktop\NodeJs\_appitry-social-node\Twitter\TwitterRoutes.js:73:71)
    at Layer.handle [as handle_request] (C:\Users\EG\Desktop\NodeJs\_appitry-social-node\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\EG\Desktop\NodeJs\_appitry-social-node\node_modules\express\lib\router\route.js:137:13)

**Comment by mynetx** [comment]
@shaheryar1 Please note that Codebird itself does not include nor provide any Promises library. Can you ensure to have loaded one of the supported libraries?

* jQuery Deferred
* Q
* RSVP
* when

You can find [more info here](https://github.com/jublo/codebird-js#use-promises-instead-of-callback-functions).
